### ISSUE TITLE
Interface redesign

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1021]
### Is your feature request related to a problem? Please describe.

The current design limits what kind of information can be conveyed efficiently, and some useless information is displayed on the pages.

#### Problems with current design

- Network health does not help reasoning about the state of the network
- Server health is an arbitrary number and notes do not rely enough context
- Command usage numbers become useless after few months
- Network servers tab limits how much information can be displayed about a server in a quick glance, requiring users to go to the server page for more information
- All placeholders are replaced in java code, making Plan webserver crucial part of the software
- jQuery data-tables are parsed from DOM, which is more expensive than using JSON
- Graph data is included in the html inside a script tag, making the file a lot larger to transmit.
- Color picker does not change color above currently chosen color until refreshing the page
- Used template uses Bootstrap 3 and updating to 4 is not worth it
- Some displayed information is calculated in java code when it could be done in an SQL query.
- Server does not know what access level the viewer has, all users need to be displayed the same page

### Describe the solution you'd like

Interface redesign with a more up to date template.

Requirements:

- Data transferred with JSON instead of in html
- Context reliant information is conveyed near the data related to it

### Additional context

Current form of analysis uses quite a lot of memory. Optimizing this could be achieved during the redesign.

**Comment by Rsl1122** [comment]
Preview of redesign that still needs some work to use JSON instead of hardcoded values:
https://rsl1122.github.io/Plan-page-preview/

**Comment by Rsl1122** [comment]
## Fluid TODO-list for `/server` page

More steps will be added as the list progresses.

### Server Overview tab

- [x] Players online graph
- [ ] Add a JSON end point with database access
  - [ ] 7 Days
    - [ ] Unique player count
    - [ ] Unique player average
    - [ ] New player count
    - [ ] New player retention
    - [ ] Average TPS
    - [ ] Low TPS spikes
    - [ ] Server downtime
  - [ ] Numbers
    - [ ] Total player count
    - [ ] Regular player count (Activity index 2.5+ query)
    - [ ] Online player count
    - [ ] Last player peak
    - [ ] Highest player peak
    - [ ] Playtime total
    - [ ] Average playtime / player
    - [ ] Session count
    - [ ] Player kill count
    - [ ] Mob kill count
    - [ ] Death count
  - [ ] Week comparison
    - [ ] Unique players 7 days before
    - [ ] Difference (trend)
    - [ ] New players 7 days before
    - [ ] Difference (trend)
    - [ ] Regular players 7 days before
    - [ ] Average playtime 7 days before
    - [ ] Average playtime last 7 days
    - [ ] Difference (trend)
    - [ ] Sessions, player kills, mob kills, deaths 7 days before
    - [ ] Sessions, player kills, mob kills, deaths last 7 days
    - [ ] Difference (trend)

**Comment by Rsl1122** [comment]
Suggestion on discord:

> Put the unique players graphic for the network as well so we can observe better how much players do we have per day on the whole network
> ~Luke#2700

**Comment by Rsl1122** [comment]
Suggestions via PM on discord, content reworded:

- [ ] Optimizing font weight loading from Google Fonts (not all fonts are needed)
- [ ] Look into Latin Extended font for special characters possibly added with Locale
- [ ] Use more of a template approach to avoid duplicate starts & ends of the html files, eg `header.html`, `footer.html` + `network.html` would only have the content

**Comment by Rsl1122** [comment]
# Fluid TODO-list for `/player` page

More steps will be added as the list progresses.

- [ ] Player name

### Player overview tab

- [ ] Information card
  - [ ] Online / Offline
  - [ ] Titles (Operator / Banned)
  - [ ] Times kicked
  - [ ] Player kills, Mob kills, Deaths
  - [ ] Total Playtime, Active playtime, afk time
  - [ ] Session count, Longest session, Session median/average
  - [ ] Activity index & group
  - [ ] Favorite server (Most played server)
  - [ ] Average ping, Worst ping, Best ping
  - [ ] Registered, Last Seen
- [ ] Nicknames
- [ ] Connection information
- [ ] Punchcard
- [ ] Online activity
  - [ ] Playtime 30d, 7d
  - [ ] Active playtime, percentage 30d, 7d
  - [ ] AFK time, percentage 30d, 7d
  - [ ] Average session length ..
  - [ ] Session count ..
  - [ ] Player kills ..
  - [ ] Mob kills ..
  - [ ] Deaths ..

### Sessions tab

- [ ] Session calendar
- [ ] World Playtime
- [ ] Recent sessions

**Comment by Rsl1122** [comment]
# Fluid `TODO`-list for `/network` page

More steps will be added as the list progresses.

## Network Overview page

- [ ] Network players online graph
- [ ] Unique and New graph
- [ ] Players
  - [ ] Unique players 24h, 7d, 30d
  - [ ] New players ...
- [ ] Numbers
  - [ ] Total players
  - [ ] Regular players
  - [ ] Online players
  - [ ] Last peak
  - [ ] All time peak
  - [ ] Total playtime
  - [ ] Avg playtime / Player
  - [ ] Average session length
  - [ ] Session count
- [ ] Week comparison
  - [ ] Unique players 7 days before, last 7 days, trend
  - [ ] New players ...
  - [ ] Regular players ...
  - [ ] Average playtime / Player ...
  - [ ] Average session length ...
  - [ ] Session count

### Servres tab

- [ ] Server containers
  - [ ] Registered player count
  - [ ] Server name
  - [ ] Online players graph
  - [ ] Last peak
  - [ ] All time peak
  - [ ] Unique players (Last 7 days)
  - [ ] New Players (Last 7 days)
  - [ ] Low TPS Spikes (Last 7 days)
  - [ ] Server downtime (Last 7 days)

**Comment by Rsl1122** [comment]
<details>
<summary>Moved feature images</summary>

![Health - Downtime](https://user-images.githubusercontent.com/24460436/63605646-0e4bcd00-c5d7-11e9-96d6-dfe004988fad.jpg)
![Health - Regular Playres](https://user-images.githubusercontent.com/24460436/63605647-0e4bcd00-c5d7-11e9-9858-34bdaf244dba.jpg)
![Player - Registered](https://user-images.githubusercontent.com/24460436/63605648-0ee46380-c5d7-11e9-96fd-8b7ff41ee664.jpg)
![Player numbers](https://user-images.githubusercontent.com/24460436/63605650-0ee46380-c5d7-11e9-875d-993954e1c4fb.png)
![Recent Login list](https://user-images.githubusercontent.com/24460436/63605651-0ee46380-c5d7-11e9-9bbd-23391923cf2a.jpg)
![Unique Players Graph](https://user-images.githubusercontent.com/24460436/63605652-0ee46380-c5d7-11e9-8e63-c153cee97961.jpg)

</details>

**Comment by Rsl1122** [comment]
# `TODO`-list for `/players` page

- [ ] Back button (Similar to error page)
- [ ] Single tab (Players)
  - [ ] Players table
  - [ ] JSON for the players table
- [ ] Update notification

**Comment by Rsl1122** [comment]
Bug reported by @mibby on Discord

- /server page Player list does not display the correct players, as some most recent players are missing

### Other issues noticed while confirming bug:

#### Bugs

- Server occupied displays 102%
  - Server Occupied ~29d 18h 25m 25s (102.37%)
  - Server Downtime (No Data) | 22h 7m 10s
- New player retention displays 0%
  - New Player Retention | (0/478) 0% | (0/115) 0% | (0/11) 0%
  - New to Regular | 152 (Would imply players were retained)
- Server Calendar comes out of the surrounding container when all days have 4 entries
- Player page nickname table does not translate color codes to colors

#### Other

- During Low TPS Spikes averages would be more useful with averages from non-tps spikes as well
  - Performance Insights could encourage the user to compare the 'as Numbers' table to the low tps averages
- Small trends could have the number in title property (on hover)
- Online Activity as Numbers would benefit from Average Playtime / Player / Day
- "Comparing ... Days" could use a title property to explain more
- Ping table could use 'ms' units
- Information about the plugin is outdated (Missing contributors)

**Comment by Rsl1122** [comment]
# List of "easy to find" optimizations

- [ ] Optimize /network server queries (Currently queries one server at a time)
- [x] Optimize Analysis graph queries
- [ ] Optimize /server playerlist query (Memory impact)
- [ ] Optimize /players playerlist query (Memory impact)

**Comment by Rsl1122** [comment]
## Related package restructuring

Since the version will be increased to 5.0 this opportunity can be taken to restructure the packages.

Here is a simplified image of the systems that are on the plugin
![Ideal Plan architecture](https://user-images.githubusercontent.com/24460436/63962551-c11aa000-ca9b-11e9-96e1-978a91e7c0ab.png)

Draft of a better package structure
```
Module: common

com.djrapitops.plan
    System
    commands
        CommandProcess
        subcommands
    settings
        locale
        theme
    identification
    gathering
        GatheringProcess
        domain
        extensions
        import
        events
        timed
    storage
        upkeep
        files
        database
            transactions (gathering)
            queries (delivery)
    delivery
        upkeep
        domain
            mutators
        rendering
            extensions
            json
            html
        export
        webserver
            cache
            response
    module

Module: platform

com.djrapitops.plan
    gathering
        listeners (abstracts on top of events)
        timed
    identification
```

**Comment by Rsl1122** [comment]
```
java.lang.NullPointerException: null
        at com.djrapitops.plan.delivery.webserver.response.Response.send(Response.java:132) ~[Plan-5.0%20ALPHA%20build%20%25buildNumber%25.jar:?]
        at com.djrapitops.plan.delivery.webserver.response.RedirectResponse.send(RedirectResponse.java:40) ~[Plan-5.0%20ALPHA%20build%20%25buildNumber%25.jar:?]
        at com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:113) [Plan-5.0%20ALPHA%20build%20%25buildNumber%25.jar:?]
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source) [?:1.8.0_221]
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source) [?:1.8.0_221]
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source) [?:1.8.0_221]
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source) [?:1.8.0_221]
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source) [?:1.8.0_221]
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```
- [ ] Fixed

**Comment by Rsl1122** [comment]
Exception when reloading after setting `Plugin.Logging.Create_new_locale_file_on_next_enable` to `true` (Exception due to new modification to the setting during boot)

```
[21:30:55 WARN]: Exception in thread "Thread-7"
[21:30:55 WARN]: java.lang.NullPointerException
[21:30:55 INFO]: [Plan] Locale: 'Custom' by
[21:30:55 WARN]:        at com.djrapitops.plan.identification.ServerInfo.getServerUUID(ServerInfo.java:47)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.network.ServerSettingsManager.updateConfigInDB(ServerSettingsManager.java:114)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.network.ServerSettingsManager.lambda$prepareFileWatcher$0(ServerSettingsManager.java:100)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.upkeep.WatchedFile.modified(WatchedFile.java:46)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.upkeep.FileWatcher.actOnModification(FileWatcher.java:120)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.upkeep.FileWatcher.handleEvent(FileWatcher.java:114)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.upkeep.FileWatcher.pollEvents(FileWatcher.java:101)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.upkeep.FileWatcher.runLoop(FileWatcher.java:95)
[21:30:55 WARN]:        at com.djrapitops.plan.settings.upkeep.FileWatcher.run(FileWatcher.java:76)
```

- [ ] Fixed

**Comment by SlimeDog** [comment]
Spigot 1.14.4 (Jenkins 2472) git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Plan 5.0-b155

No changes to 4.9.4 config.yml. Per migration instructions, removed web customizations and theme.yml. Looking good, although I despair of migrating my massive customizations.

Two initial issues:
- In dark mode (thanks for that), Session list entries are green (or default).
- PlayerList displays 5 identical copies of the single player on my test server.

**Comment by Rsl1122** [comment]
In dark mode the colors are preserved, but their contrast is reduced, do you think the reduced teal is too harsh for the eyes still?

**Comment by SlimeDog** [comment]
Yes, too harsh in dark mode. But is there a reason that 
>ParsedElements.SessionAccordion

doesn't set it? I would like the option.

**Comment by Rsl1122** [comment]
It is set by the color-selector.js when night mode is engaged (it works by inserting an extra style block into the document)

**Comment by SlimeDog** [comment]
OK. So the old customization tricks will work?
plugins/Plan/web/js/color-selector-js

**Comment by Rsl1122** [comment]
Yes they should work, let me know if they don't (that would be a bug)

**Comment by SlimeDog** [comment]
That trick will affect *all* dark mode teal backgrounds. Can I touch just the one?

**Comment by Rsl1122** [comment]
You can add a `#tableAccordion .bg-teal` rule

**Comment by SlimeDog** [comment]
Since you asked, I tested
> .bg-teal {background-color: #44475a;color: #eee8d5;}'

(borrowed from .bg-night). It works fine. No bugs here. :)

**Comment by SlimeDog** [comment]
I'm curious: Why tabs for _Performance_, but pulldown menus for _Online Activity_ and _PlayerBase_? Sure, foolish consistency is the province of small minds, but still...

**Comment by SlimeDog** [comment]
IMHO, all of the background colors for table column titles need to be toned down by quite a bit, in dark mode. Is there a contrast factor that can be configured?

**Comment by Rsl1122** [comment]
> I'm curious: Why tabs for Performance, but pulldown menus for Online Activity and PlayerBase? Sure, foolish consistency is the province of small minds, but still..

The tabs are used when there are mulpitple graphs for the section. (Tabs are also used on Online Activity Overview). The performance numbers are displayed alongside the graphs. Why the graphs aren't displayed in separate components is because larger vertical scrollbar would affect all pages.

Tabs would not fit Online Activity or Player base, because the pages consist of different layouts (I tried to make each page quickly distinguishable from each other)

I don't have anything against pulldown for performance other than current layout was easier to implement. If I were to split the page I would make a page for the numbers and page for all the graphs vertically stacked. 

I appreciate the feedback - I noticed that the tabs reset when the page is loaded again, which is a usability problem that needs resolving.
I can't remember if there is an animation when the tab switches, but removing that would make comparing the graphs easier.

**Comment by Rsl1122** [comment]
> IMHO, all of the background colors for table column titles need to be toned down by quite a bit, in dark mode. Is there a contrast factor that can be configured?

I'll probably need to write some code that handles toning down the colors since current colors are hardcoded. After that I'll add an option to theme.yml

**Comment by SlimeDog** [comment]
Sounds great. Thanks for all the information.

**Comment by Rsl1122** [comment]
It's good to have lists to keep track of all the things that need doing.

Collection of bugs & improvements that have been found after beta launch:

- [ ] Best ping & Worst ping are flipped on /network page
- [ ] Colors in night mode are still too bright
  - [ ] The adjustment should take theme.yml into account (Add a filter with code or something)
- [ ] LuckPerms Extension is giving odd group listings (Either bug in the Extension or the query for Groups (Likely the query for player table data))
- [ ] Players table contains duplicate entries in some cases
- [ ] Tabs reset when the page is refreshed / the user uses back arrow
- [ ] Tabs have a fade animation that makes it more difficult to compare two graphs
- [ ] ServerCalendar should be visible without scrolling

Other things I feel like need doing:

- [ ] Bukkit / Sponge servers should disable the Webserver automatically if Bungee or Velocity is detected in the database
  - Notify that the behavior can be disabled by setting the bungee/velocity as uninstalled in the database
- [ ] When values json fails to load (Eg server overview numbers), a warning should be displayed on that page
- [ ] When json fails to load the error should include a link where the full error can be viewed
- [ ] Jquery data-tables throws an alert in users face if a table fails to load (`DataTables warning: table id=DataTables_Table_0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`) - Figure it out
- [ ] Optimize Ping graph query by grouping the data with the date functions
- [ ] Split Session object into a gathering.domain.Session and delivery.domain.Session to improve memory performance for online sessions
- [ ] Investigate Session object leak reported on Spigot (I'm guessing it is related to `ResponseCache` holding a `ServerPageResponse`, which held a `ServerContainer`, which held a `ServerKeys.SESSIONS`, which included all of the online `Session`s at the time of analysis - If that guess is correct then the issue is fixed since ResponseCache has been removed.)
- [ ] Cache server Extension related data so that it does not need to be queried every page refresh.
- [ ] Remove IP related code
- [ ] Remove Command Usage related code
- [ ] DB Schema changes (Do this very last)
  - [ ] Drop IP column from plan_ips (Maybe rename the table)
  - [ ] Drop command usage table
  - [ ] Write a patch that replaces `uuid` & `server_uuid` with `user_id` & `server_id` in `plan_ping` - This is to reduce the space this table is taking up.

**Comment by SlimeDog** [comment]
Good list. Nothing to add. We look forward to the next drop.

**Comment by Rsl1122** [comment]
<details>
<summary>Error on /player page related to extension query</summary>

```
com.djrapitops.plan.exceptions.ParseException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: SELECT plugin_id,table_id,col_1_value,col_2_value,col_3_value,col_4_value FROM plan_extension_user_table_values JOIN plan_extension_tables on plan_extension_tables.id=plan_extension_user_table_values.table_id WHERE uuid=?; Column 'col_5_value' not found. | Failed to parse player page
    com.djrapitops.plan.delivery.rendering.pages.PlayerPage.toHtml(PlayerPage.java:86)
    com.djrapitops.plan.delivery.webserver.response.pages.PageResponse.(PageResponse.java:50)
    com.djrapitops.plan.delivery.webserver.response.ResponseFactory.playerPageResponse(ResponseFactory.java:200)
    com.djrapitops.plan.delivery.webserver.pages.PlayerPageHandler.getResponse(PlayerPageHandler.java:80)
    com.djrapitops.plan.delivery.webserver.ResponseHandler.tryToGetResponse(ResponseHandler.java:147)
    com.djrapitops.plan.delivery.webserver.ResponseHandler.getResponse(ResponseHandler.java:94)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:99)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failed: SELECT plugin_id,table_id,col_1_value,col_2_value,col_3_value,col_4_value FROM plan_extension_user_table_values JOIN plan_extension_tables on plan_extension_tables.id=plan_extension_user_table_values.table_id WHERE uuid=?; Column 'col_5_value' not found.
    com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:37)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:55)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:226)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery.executeQuery(ExtensionPlayerTablesQuery.java:67)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery.executeQuery(ExtensionPlayerTablesQuery.java:57)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:226)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerDataQuery.executeQuery(ExtensionPlayerDataQuery.java:70)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerDataQuery.executeQuery(ExtensionPlayerDataQuery.java:57)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:226)
    com.djrapitops.plan.delivery.rendering.pages.PageFactory.inspectPluginTabs(PageFactory.java:126)
    com.djrapitops.plan.delivery.rendering.pages.PlayerPage.parse(PlayerPage.java:112)
    com.djrapitops.plan.delivery.rendering.pages.PlayerPage.toHtml(PlayerPage.java:84)
    com.djrapitops.plan.delivery.webserver.response.pages.PageResponse.(PageResponse.java:50)
    com.djrapitops.plan.delivery.webserver.response.ResponseFactory.playerPageResponse(ResponseFactory.java:200)
    com.djrapitops.plan.delivery.webserver.pages.PlayerPageHandler.getResponse(PlayerPageHandler.java:80)
    com.djrapitops.plan.delivery.webserver.ResponseHandler.tryToGetResponse(ResponseHandler.java:147)
    com.djrapitops.plan.delivery.webserver.ResponseHandler.getResponse(ResponseHandler.java:94)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:99)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Column 'col_5_value' not found.
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
    com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1078)
    com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5175)
    plan.com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery.extractTableRow(ExtensionPlayerTablesQuery.java:107)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery.access$100(ExtensionPlayerTablesQuery.java:57)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery$1.processResults(ExtensionPlayerTablesQuery.java:95)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery$1.processResults(ExtensionPlayerTablesQuery.java:83)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:66)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:52)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:226)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery.executeQuery(ExtensionPlayerTablesQuery.java:67)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerTablesQuery.executeQuery(ExtensionPlayerTablesQuery.java:57)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:226)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerDataQuery.executeQuery(ExtensionPlayerDataQuery.java:70)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionPlayerDataQuery.executeQuery(ExtensionPlayerDataQuery.java:57)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:226)
    com.djrapitops.plan.delivery.rendering.pages.PageFactory.inspectPluginTabs(PageFactory.java:126)
    com.djrapitops.plan.delivery.rendering.pages.PlayerPage.parse(PlayerPage.java:112)
    com.djrapitops.plan.delivery.rendering.pages.PlayerPage.toHtml(PlayerPage.java:84)
    com.djrapitops.plan.delivery.webserver.response.pages.PageResponse.(PageResponse.java:50)
    com.djrapitops.plan.delivery.webserver.response.ResponseFactory.playerPageResponse(ResponseFactory.java:200)
    com.djrapitops.plan.delivery.webserver.pages.PlayerPageHandler.getResponse(PlayerPageHandler.java:80)
    com.djrapitops.plan.delivery.webserver.ResponseHandler.tryToGetResponse(ResponseHandler.java:147)
    com.djrapitops.plan.delivery.webserver.ResponseHandler.getResponse(ResponseHandler.java:94)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:99)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
```

</details>

**Comment by SlimeDog** [comment]
Spigot 1.14.4 latest
Plan 5.0-RC-b196 (also b190)
MacOS Mojave 10.14.6

Safari 13.0.1 (14608.2.11.1.11)
Firefox 69.0.1
Chrome 77.0.3865.90

For all browsers, the View setting is default (aka Actual Size), ie., no zoom.

Can the default font size(s) be adjusted? Not for the entire browser -- other pages are displayed as I want. Text on the Plan pages is larger than other pages, and many fields wrap, even though my browser window is very wide.

**Comment by Rsl1122** [comment]
Could you send a screenshot? :)

**Comment by SlimeDog** [comment]
For comparison, I include a SpigotMC screen. Both screens are set to the default View size, ie., no zoom. The window is 1485 pixels wide.

For the Plan screen:
- The lefthand menu text appears at the default size.
- The subpane text is all larger.
- **Week Comparison** date spans wrap.
- **Week Comparison**  "Average Playtime / Player" wraps.

![Screen Shot 2019-09-29 at 10 00 07 PM](https://user-images.githubusercontent.com/17748923/65850724-d38b3200-e304-11e9-9773-e2026f09c2f0.png)

![Screen Shot 2019-09-29 at 10 00 24 PM](https://user-images.githubusercontent.com/17748923/65850727-db4ad680-e304-11e9-9f16-e4c9716f28c2.png)

If I extend the window to 1530 pixels wide, the **Week Comparison** date spans no longer wrap. (For reference, the display is ~2230 pixels wide.)

If possible, I would like to set the default baseline font size, and hope that other font sizes scale relative to the baseline.

**Comment by SlimeDog** [comment]
This is how it should present -- this is zoomed out 1 click:
![Screen Shot 2019-09-30 at 8 49 15 AM](https://user-images.githubusercontent.com/17748923/65895210-f26ae200-e35f-11e9-8844-fd2b47ecdd0c.png)

**Comment by Rsl1122** [comment]
Since everything is based on `rem` units it is possible to scale everything based on `font-size` attribute of the `<html>` element.

I have added the following in build 204 - It reduces `font-size` from 16.5px to 16px on screens smaller than 1500px.
```
@media (max-width: 1500px)  {
    html {
        font-size: 16px;
    }
}
```
build 204 is available here
https://plan.djrapitops.com/job/Player%20Analytics/job/development/

**Comment by SlimeDog** [comment]
That doesn't seem to work. Is the test max-width == 1500px or max-width < 1500px ?

BTW, build 205 is self-identified as build 204.

**Comment by Rsl1122** [comment]
max-width means the block inside is applied when window width <= 1500px

**Comment by SlimeDog** [comment]
OK. I don't see any reduction in the display. The css code block is definitely present in the page source.

**Comment by Rsl1122** [comment]
Do things change when you make the window larger or smaller? (16 might be the default font-size on Safari, which would explain if there is no difference)

**Comment by SlimeDog** [comment]
The font-size does not appear to change as I move back-and-forth across the 1500px boundary.

**Comment by Rsl1122** [comment]
It looks like Chrome had 16px as default as well.

I have changed it to a relative reduction (95%) and that seems to work as intended on all browsers. (Tip from https://stackoverflow.com/a/13669422) - Should be good enough for other users as well. :)

**Comment by SlimeDog** [comment]
Excellent. Thanks.

Perhaps reduction should be based on a proportional comparison: windowWidth/baseWidth ?

**Comment by Rsl1122** [comment]
> windowWidth/baseWidth

Unfortunately it's very difficult to get something that reduces it correctly (I don't know a way to do this with just css)

I tried something similar in another project when an svg image went outside of its box, and gave up after trying to fix the issues with it (a big can of worms) for the whole day.

**Comment by SlimeDog** [comment]
Thanks. I'm good with 95%. :)

**Comment by SamB440** [comment]
Installed the latest plan 5, and noticed some issues w/ buycraft integration:

Module is quite small (even on 2k/4k monitor!):
![image](https://user-images.githubusercontent.com/11319274/66223588-c3d86880-e6cb-11e9-95f1-ed970bda16d4.png)
It also has nearly no padding on some parts of that module.

Also, is it possible to get the buycraft graph back?

**Comment by Rsl1122** [comment]
> Module is quite small (even on 2k/4k monitor!):

Thanks for letting me know - I'll move plugins with 3 wide tables to their own tabs

> Also, is it possible to get the buycraft graph back?

Unfortunately I didn't implement a graph API yet to DataExtension API, so it is not possible at the moment. Implementing a graph API would delay this update by one whole month so that is why it was postponed.

Why the graph is no longer displayed is because the `PluginData` API was removed, and BuyCraft stuff was moved to DataExtension API (stores things in the database). `PluginData` was dependent on proxy<->server connections that were removed in this update. I'll try to get graphs back in 5.1 or 5.2
