### ISSUE TITLE
Configure MySQL for Jenkins

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1128]
### Is your feature request related to a problem? Please describe.

Moving CI to another service from Travis is in progress (#926) - It is being moved to a Jenkins server. MySQL stuff needs some new environment variables.

### I would like to be able to..

Run MySQL Tests on Jenkins

### Todo

- [x] Install MySQL on Jenkins server
- [x] Remove `IS_CI` env variable usage, replace with Mysql info environment variables.
- [x] Add environment variables to Jenkins pipeline
