### ISSUE TITLE
Multi-Proxy support

### ISSUE THREAD

**Issue by MastoryMd5** [plan-player-analytics/Plan#1454]
**Feature**
By multi-bungeecord i mean to connect more bungeecord istances to plan and manage them
I have multiple bungeecords and if i want data from the first bungee i have to use one managment web page for each bungeecord so i will need managment1.mycrappyserver.it and managment2.mycrappyserver.it .
This will be a huge feature that might hook to RedisBungee and show the data for the whole network and add above the "servers" the "proxies" or "bungeecord" in the left panel to view each bungeecord istance and data from the proxy.
Thx for this amazing plugin tho i love it and it's very useful.

**Comment by Rsl1122** [comment]
Current RedisBungee support syncs player online count on the graph with other bungees. It is recommended to link all Plan servers to same database and use a single Plan instance on one bungee - although that might not give all information. - If you would like to see the online sessions of the other bungee you could then have the other bungee in a separate mysql database.

----

Improving support on this aspect should remove the need for two bungee Plan instances and keep online sessions/player online status in sync on the page (I think that is the only current thing that is not kept in sync with RedisBungee set up - feel free to correct me.)

**Comment by AuroraLS3** [comment]
### TODO

- [x] Allow multiple proxy servers to register to the database
- [x] Fix any immediate issues that the assumption for single proxy server in database causes
- [ ] Correct network page online player graph so that it shows either single online graph when using RedisBungee, or a stacked player online graph if not using RedisBungee
- [ ] Make proxy servers identifiable in the Network Performance server selection
- [ ] Consider possible solutions for showing online sessions on all proxy webservers if there are multiple (Currently only shows the server where webserver is on). 
  - [ ] RedisBungee events are one option
  - [ ] another option is sending data to the Plan webserver
  - [ ] Both may cause some lingering sessions if one proxy server goes down (so a last player online series date check would need to be implemented to end sessions for offline proxy servers).
