### ISSUE TITLE
Web user access control

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1623]
### Is your feature request related to a problem? Please describe.

The problem: Current access control does not allow giving access to specific parts of the web interface, such as performance, or playtime, separately. (It is all or nothing)

This was requested on the survey.

The survey answer was requesting something like password zones, but I think a permission based approach would work better. I don't want to limit the solution to this though.

### I would like to be able to..

- Control what users can view in order to give partial access to data to some users
- Configure it (some alternatives)
  - Configure this with existing permission systems (sync with Plan users)
  - Configure with a web interface that gives me a file
  - Configure with a file
- Keep the access control config and web users in sync in the database

**Comment by Rsl1122** [comment]
## Requirement analysis

### Permission storage

- Store permissions on the "main server".
- A list of available permissions should be somewhere, it is not required to have a list of all permissions in a file on the server, perhaps on a wiki.

### Permission acquisition

A challenge exists where permissions can not be checked from a player without knowing them first. This would mean they need to be stored somewhere..

In order to make it easier for users to configure permissions for users, the permissions should be defined by a group instead. But how to find what group the player belongs in? Perhaps it would be easier to check if they have a group permission, `plan.webgroup.<group name>`.

This way there could be a relation:
- `web_user` -> `group` -> `permission` and it would be possible to do a join to get the user's permissions.

This would mean that the groups need to be stored in the database.

### Compatibility with previous versions

- User with permission level need to be given access to same things they already have permission. This can be accomplished with default permission groups.

### Modification

- Edit permissions via a file
- This can be a .yml file with the permission group names and list of permissions that is then synced to the database when the file is modified.

**Comment by AuroraLS3** [comment]
### TODO

- Add database table `plan_webgroup` with `id & name`
- Add database table with `plan_webpermission` with `id, webgroup_id and permission`
- Patch database
  - Add webgroup_id to `plan_security` table with foreign key to `plan_webgroup.id`
    - Add to the create table sql
    - Add to existing tables with a patch
  - Create default groups `legacy_level_0`, `legacy_level_1`, `legacy_level_2` for permission levels 0, 1, and 2 if the plan_security table has permission_level column
    - Set webgroup_id for the users that matches the new groups
    - Add the permissions inside `WebUser` class for these groups
  - Remove permission_level column
    - Remove from create table sql
    - Remove from existing tables with a patch
- Add a config file `web_permission_groups.yml` if https is enabled on a webserver
  - It should have the groups:
    ```yml
    legacy_level_0: # (The name of the group)
        inherit: "legacy_level_1"
        permissions:
        - "plan.page.server"
        ... etc
    ```
  - The config and database data should be kept in sync. See FileWatcher and NetworkServerConfigUpdater on how to do this (except don't store the yml, update the groups and permissions in the tables instead)
  - Ensure the group names are lowercase and don't have spaces so that they can be use
- Change queries of WebUser to query the access permissions from database (instead of having permission level)  
- Modify registration to check for permission for each group `plan.webgroup.<group_name>`
- Replace permission level in list command with the user's group name
- Add a command to change web user's group
- Add new default groups
  - admin that has access to everything + user management
  - user that has access to server, network, players, query and player pages
  - user that has access to players, query and player pages
  - user that has access to players and player pages
  - user that has access to their own player page
- Add user management to the panel
  - This page should be disabled if logins are not enabled
  - Add a new permission for the user management, don't give it to legacy_level_0 though
  - The page should list web users and their group.
  - The group should be a dropdown
  - Store the change in javascript and apply changes when apply changes button is pressed on the page
  - Add endpoint to apply changes to user groups

**Comment by AuroraLS3** [comment]
List of web permissions (Note that the json endpoints should need the page permission or json permission to avoid too many duplicates):
```
page.server
page.server.overview
page.server.online_overview
page.server.sessions
page.server.playerbase
page.server.players
page.server.geolocations
page.server.performance
page.server.plugins
page.network
page.network.overview
page.network.online_overview
page.network.sessions
page.network.servers
page.network.performance
page.network.playerbase
page.network.geolocations
page.network.plugins
page.player.self
page.player.other
page.players
page.query
page.query.create
page.query.view
page.errors
page.user_management
page.user_management.modify

json.graph.players_online
json.graph.unique_and_new
json.graph.session_calendar
json.graph.punchcard
json.graph.world_pie
json.graph.server_pie
json.graph.playerbase
json.graph.performance
json.graph.geolocations

json.overview
json.online_overview
json.playerbase_overview
json.sessions_overview
json.performance_overview
json.ping_table
json.sessions
json.network.overview
json.network.ping_table
json.network.sessions
json.network.online_overview
json.network.performance_overview
json.errors
```

**Comment by Scot-Survivor** [comment]
Is there a fork, or a branch of this? 
Curious as to what's been on this so far, cause this is something I would like + account management from #2860

**Comment by AuroraLS3** [comment]
This has lot yet been started.

**Comment by AuroraLS3** [comment]
# Progress update

![image](https://github.com/plan-player-analytics/Plan/assets/24460436/0c91a32f-123f-402f-84e5-bfb8db01e38f)

I decided to go with Sponge model of permission inheritance. This way * permissions are not required and it's easy to manage.

Even though the picture looks quite complete, it still needs the saving logic hooked up to the backend & group addition/deletion needs to be more thought out - currently the 'Add group' & 'Delete group' -buttons don't have access to the group list & we don't want to reload the page for updating it. After figuring that out it's fine-tuning like translations, test fixing & so forth.

### TODO

- [ ] Hook up Save changes button to store things in backend
  - [ ] Prevent storage if no group has manage.groups permission after update.
  - [ ] Add some feedback for this error.
- [ ] Add some feedback for when saving completed
- [ ] Add some feedback for when changes were discarded
- [ ] Hook up group addition
- [ ] Hook up group deletion
- [ ] (Possible to do later) Implement similar functions for managing what group user is in
- [ ] (Possible to do later) Implement similar functions for managing what users are in group
- [ ] Add more groups
  - [ ] 'access_nothing' with no permissions
  - [ ] (Do later) 'non_logged_in_user'
- [ ] Sort out all the translations
  - [ ] Permission descriptions
  - [ ] New navigation
- [ ] Fix tests
  - [ ] Access control tests
  - [ ] Page viewing tests
  - [ ] Translation key regression tests
