### ISSUE TITLE
Network performance tab

### ISSUE THREAD

**Issue by jiajiaxd** [plan-player-analytics/Plan#1693]
Can you add a feature to display all-bungee-server average tps?

----

*by AuroraLS3:*

### TODO

- [x] Mock up a network performance page with 
  - [x] one graph for every metric, and a server selector for laying same metrics of different servers on top of each other.
  - [x] Ping graph should be from bungee since that data is gathered
  - [x] Performance overview similar to server pages, but calculated with the selected servers
- [x] Implementation
  - [x] Load performance data of different servers when a button for the server select is pressed
  - [x] Add a performance overview endpoint that accepts multiple server uuids to average over multiple servers' data
  - [x] Wire up the endpoints and write javascript code for handling the logic that loads different servers data when requested.
- [x] Export
  - [x] ~~Remove multi-select and export json of different server's performance so that each server can be selected one by one.~~
  - [ ] Remove performance tab related code from html during export

**Comment by Rsl1122** [comment]
As in a network performance tab so to speak?
