### ISSUE TITLE
Tracking issue: The unfinished business

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1769]
Several "I'll do it later" things have slipped into/out of the code over the years. This issue tracks those things.

- Unimplemented APIs
  - [ ] DataExtension API has specifications for `Group` methods but no implementation
    - [ ] Towny and Factions have Group method definitions that don't show up on the page due to no implementation
  - [x] DataExtension API has mention of a `GraphProvider` but has no implementation
  - [x] DataExtension API needs a dynamic alternative for defining data for some plugin, but has not been implemented
  - [x] DataExtension API is using too much abstraction and duplicate code to be easy to modify
  - [ ] PageExtension API mentions web user access permissions that have not been implemented  (#1623)
  - [ ] PageExtension API mentions javascript methods for page modification that have not been implemented
- Todos
  - [x] ~~DatabaseTestCreator has a TODO for creation of test dataset for optimization testing~~ (#862)
  - [x] Extension html is still rendered in Java even though it could be moved to json+js based rendering (This would ease creation of the javascript methods for page modification too)
  - [x] Jenkinsfile and .travis.yml exists on the master branch even though these are not used
- Out of date documentation
  - [x] Javadocs has not been updated for 5.2 release (A github action for this could be created)
  - [x] html branch has not been updated for 5.2 release
  - [x] html branch update script does not exist (A github action for this could be created)
  - [x] json-endpoints documentation is out of date for 5.2 release
  - [ ] Architectural Decision Records documentation is out of date for 5.2 release
  - [x] Themes documentation is out of date for 5.2 release
  - [x] Configuration documentation is out of date for 5.2 release
  - [x] PlaceholderAPI documentation is out of date for 5.2 release
- Done work that has not been merged
  - [x] ~~query-punchcard branch contains an unfinished feature~~ #1758
  - [x] experimental-gathering branch contains unfinished work for #1746 
  - [x] Actionable tasks project has unfinished tasks (It was a poor idea as it lacks automation) https://github.com/plan-player-analytics/Plan/projects/13
  - [x] Merged PR #1439 was lost somewhere on the way and did not make it to a release, investigate if it is possible to add this feature
