### ISSUE TITLE
Server Uptime

### ISSUE THREAD

**Issue by RemainingToast** [plan-player-analytics/Plan#1845]
### I would like to be able to..
See current uptime for the servers session (no 7 day average or whatever) in the server overview and access from api respectively

----

*by AuroraLS3:*

### TODO

- [x] Data acquisition
  - [x] Track current uptime by storing server enable time in a static variable. Good approach would be to do this in a static block so that the time is not affected by reloads
  - [x] Write a query that fetches time from `plan_tps` where there is a gap to previous data point is larger than 2 minutes.
  - [x] Write a method that returns either the accurate value or the queried value based server UUID ("Is it the current server")
- [x] Data transfer
  - [x] Add uptime variable to server overview JSON endpoint
  - [x] Add uptime variable to network overview JSON endpoint
  - ~~Add uptime variable to performance overview JSON endpoint~~
  - [x] Add uptime to servers endpoint (for quick view)
- [x] Visualization
  - [x] Add spot for the variable in `server.html` and `network.html`
  - [x] Add function calls to `server-values.js` and `network-values.js` to place the data on the html from previous step

**Comment by AuroraLS3** [comment]
Following query finds gaps over 2 minutes from tps data
```sql
SELECT 
    d1 AS date,
    d2 AS previous,
    d1 - d2 AS diff
FROM (
   SELECT
      -1+ROW_NUMBER() over (ORDER BY DATE) AS previous_rn,
      DATE AS d1
   FROM plan_tps
) t1
JOIN
(
   SELECT
      ROW_NUMBER() over (ORDER BY DATE) AS rn,
      DATE AS d2
   FROM plan_tps
) t2 ON t1.previous_rn=t2.rn
WHERE d1 - d2 > 120000;
```
Writing this down since it could be useful in the future.

Taking `MAX(d1)`, group by server_id from this query results in the latest start time of each server. (It should also be checked if the server is online when giving uptime because otherwise uptime will be too large.)
