### ISSUE TITLE
Tracking issue: Update to Gradle 7

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1871]
### Is your feature request related to a problem? Please describe.

Upgrade to Gradle 7 might speed up compilation times

Deprecated features in use incompatible with 7:

- [x] `compile` has been deprecated for dependency declaration
- [x] `testCompile` has been deprecated for dependency declaration
- [x] The AbstractArchiveTask.baseName property has been deprecated. plugin\build.gradle:30
- [x] The AbstractArchiveTask.destinationDir property has been deprecated. plugin\build.gradle:29

### I would like to be able to..

Upgrade to gradle 7 https://docs.gradle.org/current/userguide/upgrading_version_6.html

- [x] List the deprecated things
- [x] Update plugins
- [x] update project to 7 with `gradle wrapper --gradle-version 7.0`
- [x] Debug any errors https://docs.gradle.org/current/userguide/troubleshooting.html#troubleshooting
