### ISSUE TITLE
Show Plan version number in /plan servers to help network admins maintain their server

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2245]
### I would like to be able to..

Get version of Plan running on all servers in the network

### Is your feature request related to a problem? Please describe.

An old version can insert bad data in some cases if the schema gets a new field with a default value. This is usually countered by database patches, but some patches can take too long and lead to issues in the up-to-date versions

### TODO

- [x] Add new field to plan_servers called plan_version
- [x] Have default value be null and update version in there on enable.
- [x] Add the plan version to /plan servers command
- [x] Show "Older" on anything that tries to read the value if it is null since old versions will not insert this data, but the version that can view this data can still query it.
