### ISSUE TITLE
Track plugin versions for performance tab.

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#2360]
### Data to display

Your performance infomration is amazing, but most of the time the reason performance is dipping is becase of a plugin.
This is sometimes when a plugin is updated or a specific version, if you could track plugin versions over time, then you could show statistics on the performance page that show if a plugin(s) was updated to say with poorer performance.
You would only need to collect this information when the server boots too! So no constant tracking required for plugin versions!

Bonus points if when you click on a plugin, you can open its Spigot page/website and also link to the Bstats page.

In time, you will be able to have a new tab under performance that includes "plugins", where you can track performance based on plugins over time, hell, you could even see if more entities are about based on plugins that change entities too as you already have this data!

If you want to get even more mental, you could detect a TPS drop and autoamtically create a timings report, which im sure has an API to then pull a plugin that could be a top offender! 

You could also hook into coreprotect, that way you could click on an event where theres been a TPS drop and you could load the Chat/commands that were used by players around that time, so try and see if they ran a command that casued it.

Alternativly, Pull from server logs around that time!

### Link to API or Source Code

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/plugin/PluginDescriptionFile.html#getVersion()

### Link to Project page or Downloads

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/plugin/PluginDescriptionFile.html

**Comment by AuroraLS3** [comment]
Tracking plugin versions over time is a good idea. I'll have to see if it's possible to get that data also for non bukkit servers.

I think running timings is a bit out of scope for Plan just because of the complexity of detecting tps drops while they're happening (The TPS calculation often depends on how fast server is running, and so TPS itself)

CoreProtect idea is good, especially the command use one. I think you have found a good use case for implementing #1240, as tracking commands would also allow linking use of some commands to a TPS spike through analysis of the data.

**Comment by CreeperODeath** [comment]
If you can track plugin versions then it might be possible to set it up where it can check for updates
but I feel that might be outside of the scope

**Comment by AuroraLS3** [comment]
I have some good news!

### TODO

- [x] Extract this data from servers
  - [x] Bukkit
  - [x] Bungeecord
  - [x] Nukkit
  - [x] Sponge
  - [x] Fabric
  - [x] Velocity
- [x] Store this data
- [ ] Add visualization for this data

**Comment by AuroraLS3** [comment]
Teaser images
![image](https://github.com/plan-player-analytics/Plan/assets/24460436/ebf44b4b-2d0d-4a1c-b360-194cd6fd54fe)
![image](https://github.com/plan-player-analytics/Plan/assets/24460436/818e79a4-01f6-491f-867b-5b7f045fff28)

**Comment by TomLewis** [comment]
This is absolutely fantastic solution! 
This will come in very handy!
