### ISSUE TITLE
Tracking issue: More kill chains

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2427]
### I would like to be able to..

See more kill chains that can occur in vanilla gameplay and attribute the mob and player kills appropriately

### Is your feature request related to a problem? Please describe.

Currently a lot of kill chains are counted already (A player shooting an arrow into endcrystal killing a player for example), but there are more ways to kill.

Player/mob can get killed by (Entries without tickbox don't need to be counted since they aren't triggered by players):

- [ ] TNT/TNT minecart explosion chain, TNT can be triggered by
  - [ ] Flint & steel / Firecharge / Fire
    - [ ] Fire spread may not be tracked by game server
  - [ ] Arrows / eggs / snowballs / fishing lines on fire
  - [ ] Fire aspect / Flame weapons
  - [ ] Another explosion
    - Creeper
    - Ghast
    - [ ] TNT
    - [ ] Bed
    - [ ] Respawn anchor
    - [ ] End crystal
    - Wither skull
  - [ ] Dispensed directly
  - [ ] Redstone
  - Enderdragon flying through
  - [ ] Hit by lightning
    - [ ] Channeling enchantment on a trident during rainfall
- [ ] Bed / Respawn anchor explosion
- [ ] Being set on fire
  - [ ] Flint & steel / firecharge / Arrows / eggs / snowballs / fishing lines on fire
  - [ ] Lava bucket use
  - [ ] Hit by lightning
    - [ ] Channeling enchantment on a trident during rainfall
- [ ] Dying by falling onto blocks that deal damage
  - [ ] Soul campfires / dripstones
- [ ] Dying by dropping dripstones on top
  - [ ] Dripstone falling cause likely not tracked by server
    - [ ] Block broken above the dripstone
    - Gravel/sand causing blocks to fall (Difficult to track)
- [ ] Projectiles fired from dispenser, dispenser can be triggered by
  - [ ] Redstone directly
  - [ ] Redstone indirectly (clocks etc), these form some sort of activation chain that can be shortened if necessary
- [ ] Suffocation in sand/gravel placed by player
- [ ] Drowning due to player forming ice on top of the water with Frost Walker enchantment
- [ ] Fall damage if falling due to a hit or explosion chain
- Traps triggered via redstone (Too difficult to track)

There are probably more, but this list sounds pretty good starting point.

**Comment by AuroraLS3** [comment]
Marked as 'Good First Issue': If you would like to contribute, PR:ing one of the kill chains for one platform is an easy start since it will need touching the `gathering` packages and not much else, since `PlayerKill` already has `String` (30 characters) as the weapon.
