### ISSUE TITLE
DataExtension Graph API: Arbitrary graph metric sampler

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2544]
### I would like to be able to..

Gather numeric data from any source and sample it similar to the performance metrics.

### Is your feature request related to a problem? Please describe.

Data from other plugins could use some graphs.

In addition some data could be sampled automatically, such as DataExtension group development over time

To take into consideration:
- Provide a method that samples single datapoint when called
  - Allow specifying sample interval
  - Allow specifying multiple values for one datapoint
  - Allow specifying if the values should be stacked by default when graphed (In future it might be possible to allow user to choose)
  - Allow specifying formatter, time for example
- Provide a method that adds multiple samples when called
  - Strategy: REPLACE_ALL or APPEND_ALL
  - Limit REPLACE_ALL to 1000 datapoints due to replacement strategy being slow
- Support different data types
  - Double
  - Long
  - time amount
  - percentage
- Allow specifying if graph supports aggregation:
  - sum over time
  - average over time
  - min / max over time
- Allow defining x-axis
  - date by default
  - value index if defined
- Needs to provide graph metadata
  - Graph name
  - Value unit names (Use multiple y-axis if necessary, aggregate axis by unit name)
  - Series names (Since datapoint can have multiple values)
- Automatically generated cleanup strategy in the config under the specific plugin.

Special case:
- Pie / Bar chart: Single datapoint with multiple values
  - Should this support drilldown data?

Future considerations:
- PlaceholderAPI support

Implementation considerations:
- I figure it might make sense to create a new table for each graph.
- Have a metadata table for plugin-server-player-graph relations
- Have a metadata table for graph metadata
- Generate SQL using the metadata
- Access through a generic graph data endpoint
- Needs the React frontend for extensions before generic enough graphs could be easy to do.

**Comment by ItsJuls** [comment]
I would like this because graphs for 3rd party plugins would be good for a lot of things. I myself want to have metrics being graphed instead of just being number values on the plugins overview page.

**Comment by AuroraLS3** [comment]
# TODO list:

For those tracking progress on this ticket, as well as for me to remember what still needs doing

- [x] API (may be subject to change
- [x] API updates
  - [x] Add new ElementOrder values to default method body
- [x] Database storage
  - [x] Store graph metadata
  - [x] Store individual datapoints
  - [ ] Store history points
- [x] Gathering code
  - [x] Task registration/cancelation
- [x] Database queries
- [x] Webserver endpoints
- [ ] Visualization code
  - [ ] Request from frontend
  - [ ] Export system additions
  - [ ] Render graph based on data
  - [ ] Y-Axis (Units)
  - [ ] X-Axis (formatter)
  - [ ] Tooltips (formatter)
  - [ ] Stacking
- [ ] Aggregations (Considered to be split into another ticket)
- [ ] Data cleanup strategy config settings

**Comment by ItsJuls** [comment]
gta 6 will come out before this

**Comment by AuroraLS3** [comment]
It might because I am sick right now

**Comment by ItsJuls** [comment]
> It might because I am sick right now

very much get well soon its been quite a few years by now and my server still hasnt opened yet, so fair.
