### ISSUE TITLE
Database with data for optimizations

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#862]
### Is your feature request related to a problem? Please describe.

Currently database optimizations are measured with an incomplete data-set (60000 imported players, missing session data + other data), which means that optimizations are made based on incomplete information.
In addition, network operation optimization is not doable with no data.

This problem is related to the optimization of *analysis performance* and does not extend to optimization of gathering methods

### Describe the solution you'd like

I would like a database with semi-realistic, very busy network load emulating data-set.

In order to emulate real environment, some kind of Monte Carlo sampling method using sine waves might be best option for data generation.
This is because servers have peak hours.

#### Sub-issues

- [ ] Data Generation
  - [ ] 100 000 players generated for a baseline
  - [ ] 10 servers, 1 proxy
  - [ ] Online Data
    - [ ] 3 Sine-waves (one 24h, one 17 days, one 50 days) to generate baseline for online count
    - [ ] Pulse gap addition to simulate scheduled restarts
    - [ ] Random gap addition to simulate unwanted crashes
  - [ ] Some kind of Online count -> Sessions conversion has to be made.
    - [ ] Random split into WorldTimes
    - [ ] Random based kill counts (Find random player UUID for player kills)
  - [ ] Ping Data times based on the sessions, random numbers.
  - [ ] TPS data: Random numbers (Small impact on performance)
  - [ ] IP addresses: random integer x4, 1-2 per user
    - [ ] Geolocations from the random IP
  - [ ] Nicknames: Random String, 1-5 per user
- [ ] Save in big batches

**Comment by AuroraLS3** [comment]
Better approach would be to modify the event to be pipeline based #817 and then process some set of events through the pipeline to end up with an up-to-date database. This way the test doesn't need to be updated all the time.
